### ISSUE TITLE
类的命名也比较混乱

### ISSUE THREAD

**Issue by paper** [swusj/Calendar#2]
https://github.com/swusj/Calendar/blob/c7b9e7ddb77d6e321c3e884a3efc2c5a26b83970/styles/color.css#L1

类通常不使用骆驼形式，使用中横线比较多，比如 .screen-outer; 
.CurDateItem ==> .curdate-item

建议看这个：https://juejin.cn/post/6844903479698259975

**Comment by swusj** [comment]
现在先改成了横线形式
