### ISSUE TITLE
全大写连在一起是很难阅读的，需要下划线分割

### ISSUE THREAD

**Issue by paper** [swusj/Calendar#4]
https://github.com/swusj/Calendar/blob/15d5fde01fe0f35d9ef2307a89f5f3e85b50796d/scripts/config.js#L1-L13

比如：
MONTHOFLEAPYEAR => MONTH_OF_LEAP_YEAR
DAYCHENGE => DAY_CHENGE
SHOWLIST => SHOW_LIST

**Comment by swusj** [comment]
改了改了
