### ISSUE TITLE
请查看：https://developer.mozilla.org/zh-CN/docs/Web/API/Element/classList

### ISSUE THREAD

**Issue by paper** [swusj/Calendar#5]
https://github.com/swusj/Calendar/blob/15d5fde01fe0f35d9ef2307a89f5f3e85b50796d/scripts/utils.js#L120

 新增class 和 移除class 请查看 MDN 文章。

**Comment by swusj** [comment]
改了改了，我最开始是跟着DOM编程艺术那本书写的添加，想删除发现不会，去查发现已经有api了，想练习下原始写法才这样写 
>_<
