### ISSUE TITLE
如果想表达上一个 和  下一个通常命名为：prev, next

### ISSUE THREAD

**Issue by paper** [swusj/Calendar#6]
https://github.com/swusj/Calendar/blob/15d5fde01fe0f35d9ef2307a89f5f3e85b50796d/scripts/utils.js#L8
https://github.com/swusj/Calendar/blob/15d5fde01fe0f35d9ef2307a89f5f3e85b50796d/scripts/utils.js#L66

所以这里最佳是：getPrevMonth，getPrevYear

**Comment by swusj** [comment]
已改
