### ISSUE TITLE
42？42是什么？神奇数字？？常量的话最好定义一个 const 不变量来说明或表达

### ISSUE THREAD

**Issue by paper** [swusj/Calendar#7]
https://github.com/swusj/Calendar/blob/15d5fde01fe0f35d9ef2307a89f5f3e85b50796d/scripts/display.js#L121

比如：
```javascript
// 在 config.js 里面定义
const MAX_NUMBER = 42; // 当然名字要取的更有意义最佳。
```

这样这个数字就不是一个“神奇”数字了。

“神奇数字”好像出现在很多地方，可以一起排查一下。

**Comment by swusj** [comment]
改了
