### ISSUE TITLE
images 里面的两个图片

### ISSUE THREAD

**Issue by paper** [swusj/Calendar#8]
有两个改进方式：

1：首先取名改为 up.png 和 down.png

2：可以使用符号来实现：https://www.webhek.com/post/html-enerty-code.html

3：可以使用 css 来实现

4：可以使用 svg 来实现

可以都试一试。。。

**Comment by swusj** [comment]
我现在是用的css实现的，原来的图片没删，先搞完其他的再试试符号和svg
